version: '3'

services:
  postgresql:
    image: postgres:14
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store: